_target_: emergent_canonical_frame.data.eval_datasets.Objectron

split: "objectron"
data_root: "/path/to/objectron"
cate: ~
cad_root: "/path/to/imagenet3d/CAD"
fallback_mesh_root: "/path/to/fallback_meshes"
